### PR TITLE
Add GMX to providers

### PR DESCRIPTION
**Pull request by StoyanDimitrov**
Tested in the application.

### CODE REVIEW

**Comment by StoyanDimitrov** [comment]
Yes, it works. Tested in the app.

**Comment by M66B** [comment]
Thanks.

**Comment by StoyanDimitrov** [comment]
I mean tested it, but unsuccessful. The app returns message along the lines 
"Does not support IDLE".

**Comment by M66B** [comment]
Yes, I understand, but that does mean the provider is not supported yet.

See also this FAQ: https://github.com/M66B/open-source-email/blob/master/FAQ.md#FAQ5

**Comment by M66B** [comment]
Looking here: https://support.gmx.com/pop-imap/imap/server.html

SMTP should be able to be used without STARTTLS, which is more secure.

Can you please try this?

**Comment by StoyanDimitrov** [comment]
It is able to send w/o STARTTLS.

**Comment by StoyanDimitrov** [comment]
Do you want me to correct it?

**Comment by StoyanDimitrov** [comment]
> I mean tested it, but unsuccessful. The app returns message along the lines "Does not support IDLE".
That was about #31. Sorry messed up the message threads.

**Pull request merged**
